---
# Tasks for setting up a mongo config instance.
#
# Author: Valentin DAMBRINE <val.dambrine97@gmail.com>
#
# Date: March, 07th 2020

- name: Enable and start mongod service
  service:
    name: mongod
    enabled: yes
    state: started

- name: Config MongoDB
  template:
    src: mongod-cfg.conf.j2
    dest: /etc/mongod.conf
  notify:
    - restart mongod